### PR TITLE
update logic and styling for index pages

### PR DESCRIPTION
**Pull request by eshaben**
This PR updates the logic for generating index pages and makes a few minor styling adjustments. Essentially this way of generating the index pages allows us customizability while also being able to take advantage of automating the process a bit since there will be external contributors, some of this should be automated, so they don't have to really know or worry about this

This should be reviewed with `polkadot-docs` PR: https://github.com/polkadot-developers/polkadot-docs/pull/200

### CODE REVIEW

**Review by albertov19 — DISMISSED** [review]
LGTM

**Comment by eshaben** [comment]
Fixed your suggestion on the other PR here: https://github.com/polkadot-developers/polkadot-docs/pull/200#pullrequestreview-2454137773

**Comment by eshaben** [comment]
⚠️ This will need to be merged alongside polkadot-docs PR# 200, otherwise it'll break things

**Review by albertov19 — APPROVED** [review]
LGTM!

**Pull request merged**
